version: "3.1"

services:
  django_server:
    container_name: django_server
    #build:
    #  context: .
    image: myapp:latest
    ports:
      - 8000:8000
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #env_file:
    #  - speedportal/.env
    environment:
      POSTGRES_DB: 'dockertest_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
    ports:
      - 5432:5432

volumes:
  postgres_data: