# Generated by Django 4.2.6 on 2025-03-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charfield', models.TextField()),
                ('intfield', models.IntegerField(default=0)),
                ('boolfield', models.BooleanField(default=False)),
            ],
        ),
    ]
