# Generated by Django 4.2.6 on 2025-03-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='charfield',
            new_name='textfield',
        ),
    ]
